<a href="https://colab.research.google.com/github/apache2046/torch_demo/blob/main/demo1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
torch.cuda.is_available()

True

In [5]:
a=torch.randint(20, size=(3,4,5))
print(a)

tensor([[[12,  5, 19, 13,  3],
         [ 8, 11, 12,  8,  4],
         [13,  6,  4, 10, 10],
         [ 9,  1,  7, 13,  3]],

        [[ 1, 19,  1, 11,  6],
         [ 9, 14,  3,  3,  6],
         [ 0,  0,  0, 10,  4],
         [ 6, 17, 13,  9,  5]],

        [[ 0, 17,  0,  4, 18],
         [11, 12, 11, 12, 11],
         [ 8, 10,  1, 17, 15],
         [11,  2, 11, 12, 17]]])


In [8]:
b1,b2=a.split(4, dim=2)
print(b1, b1.shape)
print(b2,b2.shape)

tensor([[[12,  5, 19, 13],
         [ 8, 11, 12,  8],
         [13,  6,  4, 10],
         [ 9,  1,  7, 13]],

        [[ 1, 19,  1, 11],
         [ 9, 14,  3,  3],
         [ 0,  0,  0, 10],
         [ 6, 17, 13,  9]],

        [[ 0, 17,  0,  4],
         [11, 12, 11, 12],
         [ 8, 10,  1, 17],
         [11,  2, 11, 12]]]) torch.Size([3, 4, 4])
tensor([[[ 3],
         [ 4],
         [10],
         [ 3]],

        [[ 6],
         [ 6],
         [ 4],
         [ 5]],

        [[18],
         [11],
         [15],
         [17]]]) torch.Size([3, 4, 1])


In [9]:
c=torch.cat((b1,b2), dim=2)
print(c, c.shape)

tensor([[[12,  5, 19, 13,  3],
         [ 8, 11, 12,  8,  4],
         [13,  6,  4, 10, 10],
         [ 9,  1,  7, 13,  3]],

        [[ 1, 19,  1, 11,  6],
         [ 9, 14,  3,  3,  6],
         [ 0,  0,  0, 10,  4],
         [ 6, 17, 13,  9,  5]],

        [[ 0, 17,  0,  4, 18],
         [11, 12, 11, 12, 11],
         [ 8, 10,  1, 17, 15],
         [11,  2, 11, 12, 17]]]) torch.Size([3, 4, 5])


In [15]:
print((c==a).sum().tolist(), c.numel())

60 60
